---
name: Code checks

on:
    pull_request:
        types: ['opened', 'reopened', 'synchronize']
    workflow_dispatch:
        inputs:
            push:
              description: Push documentation changes
              required: true
              type: boolean
              default: true

jobs:
    docs:
        name: docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: check docs
              uses: ./.github/actions/terraform-docs
              with:
                push: ${{ github.event_name == 'pull_request' || inputs.push }}
